
- name: build the virtual hardware, install OS, and install apps
  ansible.builtin.import_playbook: machine.yml

- name: install supporting apps
  ansible.builtin.import_playbook: custom-os.yml

- name: install service
  ansible.builtin.import_playbook: service.yml

- name: test
  ansible.builtin.import_playbook: test-stack.yml

