# incomplete
# gitlab?
# https://hardiman.consulting/ansible/2.11/git-set-up/git-repo-shared.html

- name: build the SCM
  hosts: git1.lab.example.com
  become: yes
  gather_facts: yes
  #gather_facts: no
  vars:
    gitlab_external_url: "https://git1.lab.example.com/"
  roles:
    - role: geerlingguy.gitlab

