# gitlab?
# or keep it real simple with
# https://hardiman.consulting/ansible/2.11/git-set-up/git-repo-shared.html


- name: build the SCM
  hosts: git1.lab.example.com
  become: yes
  gather_facts: yes
  #gather_facts: no
  vars:
    gitlab_domain: git1.lab.example.com
    gitlab_ssl_certificate: "/etc/pki/tls/certs/{{ gitlab_domain }}.pem"
    gitlab_ssl_certificate_key: "/etc/pki/tls/private/{{ gitlab_domain }}.key"
    gitlab_create_self_signed_cert: no
  roles:
    - role: geerlingguy.gitlab

